# Generated by Django 5.0.4 on 2024-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
