# Generated by Django 5.0.4 on 2024-05-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
