# Generated by Django 5.0.4 on 2024-04-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
