# Generated by Django 5.0.4 on 2024-04-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
