# Generated by Django 5.0.4 on 2024-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Zapatos', 'Zapatos'), ('Camisas', 'Camisas'), ('Buzos', 'Buzos')], max_length=50),
        ),
    ]
