# Generated by Django 5.0.4 on 2024-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
