# Generated by Django 5.0.4 on 2024-05-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuser_reset_password_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
